### ISSUE TITLE
Hi, when will the instruction and scripts for building slr4e dataset be available?

### ISSUE THREAD

**Issue by kk1tsch** [SapienzaNLP/srl4e#1]
I'm very interested in your exciting work. 
Could you please tell me when the instruction or scripts for dataset will be available?
If the instruction and scripts are unavailble for some time, could you please provide annotated data?
Thank you very much.

**Comment by caesar-one** [comment]
Hi!

Thank you very much for your interest in SRL4E!

We have just pushed some scripts that can be used to convert the data to the SRL4E format. They are not final at all, but they can still be used to build the resource, so you can start working on them, waiting for a cleaner version! There may be the need to consult the code to verify the correct folder structure. In the next few days, we will be uploading a final and more robust version, along with a guide to building the resource correctly.

Regarding the data: for copyright reasons, we cannot release the data directly, but in the [DATA.md](https://github.com/SapienzaNLP/srl4e/blob/main/DATA.md) file, you will find the links and a small guide on where to find them.

**Comment by abbascs** [comment]
Hi
Is this Issue completed?
I couldn't find any instructions yet.

**Comment by caesar-one** [comment]
> Hi
> Is this Issue completed?
> I couldn't find any instructions yet.

Hi!

Check the [data/scripts](https://github.com/SapienzaNLP/srl4e/tree/main/data/scripts) folder. You can build the resource by simply running the `run.sh` file. Let us know if you have any issue with that.
