### ISSUE TITLE
evaluate metircs

### ISSUE THREAD

**Issue by evantian110** [SapienzaNLP/srl4e#2]
hello, what are your evaluation metrics，specifically the NER task? can you help me about the code, please?

**Comment by caesar-one** [comment]
Could you please clarify what do you mean by NER task? This is a benchmark for structured emotion classification. I recommend to take a look at the paper (that you find in the readme of this repo).

**Comment by evantian110** [comment]
I mean in role identification and cue identification, when calculating their f1, I used micro and macro methods respectively and their results have a large difference , so I wanted to ask which one is better， or just use conllevel package. Sorry for bothering and thanks for the reply.
&nbsp;


田宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Cesare ***@***.***&gt;; 
发送时间: 2023年7月21日(星期五) 晚上6:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SapienzaNLP/srl4e] evaluate metircs (Issue #2)





 
Could you please clarify what do you mean by NER task? This is a benchmark for structured emotion classification. I recommend to take a look at the paper (that you find in the readme of this repo).

**Comment by evantian110** [comment]
Hello, would you like to send me the source code of the experiment code, I only use it for learning.Whether you agree with it or not, thank you very much.
